---
- name: Create directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "999"
    group: "999"
    mode: '0755'
  loop:
    - "{{ postgresql_data_dir }}"
    - "{{ postgresql_wal_dir }}"
    - "/etc/patroni"
    - "/var/log/patroni"

- name: Generate Patroni configuration
  template:
    src: patroni.yml.j2
    dest: "/etc/patroni/patroni.yml"
    owner: "999"
    group: "999"
    mode: '0644'

- name: Pull Patroni image
  community.docker.docker_image:
    name: "{{ patroni_docker_image }}"
    source: pull
    force_source: yes

- name: Deploy Patroni container
  community.docker.docker_container:
    name: "{{ patroni_cluster_name }}"
    image: "{{ patroni_docker_image }}"
    state: started
    restart_policy: "{{ docker_restart_policy }}"
    network_mode: "host"
    volumes:
      - "{{ postgresql_data_dir }}:/home/postgres/pgdata"
      - "{{ postgresql_wal_dir }}:/home/postgres/pgwal"
      - "/etc/patroni/patroni.yml:/etc/patroni/patroni.yml:ro"
    env:
      PATRONI_NAME: "{{ inventory_hostname }}"
      PATRONI_SCOPE: "{{ patroni_scope }}"
      PATRONI_LOG_LEVEL: "DEBUG"
    command: "patroni /etc/patroni/patroni.yml"
    detach: true
    timeout: 120

- name: Wait for Patroni API
  uri:
    url: "http://{{ ansible_host }}:{{ patroni_restapi_port }}/health"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 30
  delay: 10