- name: ansible-minio
  src: https://github.com/atosatto/ansible-minio
  version: master
  scm: git

- name: ansible-role-nginx
  src: https://github.com/nginx/ansible-role-nginx
  version: main
  scm: git

- name: ansible-victoriametrics-cluster-role
  src: https://github.com/Slapper/ansible-victoriametrics-cluster-role
  version: master
  scm: git

- name: ansible-etcd-cluster
  src: https://github.com/freebyone/ansible-role-etcd-cluster
  version: main
  scm: git

- name: ansible-haproxy-cluster
  src: https://github.com/freebyone/ansible-role-haproxy-cluster
  version: main
  scm: git

- name: ansible-patroni-postgres
  src: https://github.com/freebyone/ansible-role-patroni-postgres-cluster
  version: main
  scm: git